apiVersion: v1
kind: Service
metadata:
  name: orders-api
spec:
  selector:
    app: orders-api
  ports:
    - name: default
      protocol: "TCP"
      port: 8080
      targetPort: 8080
    - name: admin
      protocol: "TCP"
      port: 8081
      targetPort: 8081
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api
spec:
  selector:
    matchLabels:
      app: orders-api
  replicas: 1
  template:
    metadata:
      labels:
        app: orders-api
    spec:
      containers:
        - name: orders-api
          image: orders-api:latest
          imagePullPolicy: Never
          env:
            - name: PORT
              value: "8080"
            - name: CONFIG_ENVIRONMENT
              value: k8s
            - name: DB_HOST
              value: postgresql
            - name: CUSTOM_JAVA_AGENT
              value: opentelemetry-javaagent.jar
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://signoz-otel-collector.platform.svc.cluster.local:4317"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=orders-api
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3
